TIPO_PERIODO= ( 
    ("MENSUAL", "MENSUAL"), 
    ("BIMENSUAL", "BIMENSUAL"), 
    ("TRIMESTAR", "TRIMESTAR"), 
    ("CUATRIMESTRAL", "CUATRIMESTRAL"), 
    ("SEMESTRAL", "SEMESTRAL"), 
) 

TIPO_CREDITO= ( 
    ("EDUCACION", "EDUCACION"), 
    ("EMPRENDIMIENTO", "EMPRENDIMIENTO"), 
    ("LIBRE INVERSION", "LIBRE INVERSION"),
    ("HIPOTECARIO", "HIPOTECARIO"), 
    ("VEHICULO", "VEHICULO"), 
    ("VIAJE", "VIAJE"), 
) 

GENERO= ( 
    ("FEMENINO", "FEMENINO"), 
    ("MASCULINO", "MASCULINO"), 
    ("OTRO", "OTRO"), 
) 

ESTADO_CIVIL= ( 
    ("CASADO(A)", "CASADO(A)"), 
    ("UNION LIBRE", "UNION LIBRE"), 
    ("SOLTERO(A)", "SOLTERO(A)"),
    ("VIUDO(A)", "VIUDO(A)"),
     ("SEPARADO(A)", "SEPARADO(A)"),
     ("DIVORCIADO(A)", "DIVORCIADO(A)"),
) 